version: "3"
services:
  db:
    container_name: db
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=db
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d/:ro
      
  rabbitmq:
    container_name: queue
    image: rabbitmq:3-management 
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./queue/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672